apiVersion: v1
kind: ServiceAccount
metadata:
  name: ace-pipeline-deployer-serviceaccount
  namespace: ace01-ci
secrets:
  - name: ace01-git-credentials
  - name: cpicrio-secret
  - name: image-registry-secret
  - name: quayio-secret
  - name: dockerio-secret
imagePullSecrets:
  - name: ibm-entitlement-key