apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ace01-dev
  name: ace-deployer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets", "services", "configmaps", "serviceaccounts"]
  verbs: ["*"]
- apiGroups: ["appconnect.ibm.com"] # appconnect.ibm.com API group
  resources: ["integrationservers", "configurations", "dashboards"]
  verbs: ["*"]
