apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ace01-ci
  name: pipeline-deployer
rules:

- apiGroups: ["tekton.dev"]
  resources: ["pipelines", "pipelineruns", "tasks"]
  verbs: ["*"]
