apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc
  namespace: ace01-ci
spec:
  storageClassName: lvms-vg1-immed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi