apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-argo
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ace01-ci
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/ci/pipelines/
    repoURL: https://github.com/aceorg-khongks/ace01-ops.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
